import React from 'react'

const CheckboxesStudents= function(props){

  return(<form>
      <label>
        Evelyn
        <input
          type={"checkbox"}
          name="Evelyn"
          onChange={props.onchecked}
          checked={props.checkbox.Evelyn}
        />
      </label>
      <label>
        Aranka
        <input
          type={"checkbox"}
          name="Aranka"
          onChange={props.onchecked}
          checked={props.checkbox.Aranka}
        />
      </label>
      <label>
        Floris
        <input
          type={"checkbox"}
          name="Floris"
          onChange={props.onchecked}
          checked={props.checkbox.Floris}
        />
      </label>
      <label>
        Hector
        <input
          type={"checkbox"}
          name="Hector"
          onChange={props.onchecked}
          checked={props.checkbox.Hector}
        />
      </label>
      <label>
        Martina
        <input
          type={"checkbox"}
          name="Martina"
          onChange={props.onchecked}
          checked={props.checkbox.Martina}
        />
      </label>
      <label>
        Maurits
        <input
          type={"checkbox"}
          name="Maurits"
          onChange={props.onchecked}
          checked={props.checkbox.Maurits}
        />
      </label>
      <label>
        Rahima
        <input
          type={"checkbox"}
          name="Rahima"
          onChange={props.onchecked}
          checked={props.checkbox.Rahima}
        />
      </label>
      <label>
        Sandra
        <input
          type={"checkbox"}
          name="Sandra"
          onChange={props.onchecked}
          checked={props.checkbox.Sandra}
        />
      </label>
      <label>
        Wietske
        <input
          type={"checkbox"}
          name="Wietske"
          onChange={props.onchecked}
          checked={props.checkbox.Wietske}
        />
      </label>
      <label>
        Storm
        <input
          type={"checkbox"}
          name="Storm"
          onChange={props.onchecked}
          checked={props.checkbox.Storm}
        />
      </label>
    </form>)
}
export default CheckboxesStudents
